import type { ContextForgeConfig } from "../config/configSchema.js";
import type { InstalledPack, PackFileType } from "../registry/registrySchema.js";
import type { GeneratedFile, ProjectAnalysis } from "../types.js";

function normalizeOutputPath(outputPath: string): string {
  return outputPath.split(/[\\/]/u).join("/");
}

function defaultOutput(packName: string, type: PackFileType): string | null {
  const defaults: Record<PackFileType, string | null> = {
    rules: null,
    agents: `.contextforge/instructions/agents/${packName}.md`,
    claude: `.contextforge/instructions/claude/${packName}.md`,
    skill: `.agents/skills/${packName}/SKILL.md`,
    cursor: `.cursor/rules/${packName}.mdc`,
    copilot: `.github/instructions/${packName}.instructions.md`
  };

  return defaults[type];
}

function shouldGenerateFile(type: PackFileType, tools: ContextForgeConfig["tools"]): boolean {
  if (type === "agents") {
    return tools.includes("codex");
  }

  if (type === "claude") {
    return tools.includes("claude");
  }

  if (type === "skill") {
    return tools.includes("codex") || tools.includes("claude");
  }

  if (type === "cursor") {
    return tools.includes("cursor");
  }

  if (type === "copilot") {
    return tools.includes("copilot");
  }

  return false;
}

function compileRootAgents(packs: InstalledPack[], analysis: ProjectAnalysis): string {
  const summaries = packs
    .map((pack) => pack.files.agents?.trim())
    .filter((summary): summary is string => Boolean(summary));
  const gitSafetyWarning = packs.some((pack) => pack.manifest.name === "git-workflow")
    ? [
        "## Git Safety",
        "",
        "Do not commit, push, merge, rebase, reset, delete branches, or rewrite history unless explicitly requested by the user.",
        ""
      ]
    : [];

  return [
    "# Project Agent Instructions",
    "",
    "Generated by ContextForge from installed instruction packs.",
    "",
    "## Core Behavior",
    "",
    summaries.length > 0 ? summaries.join("\n\n") : "No pack-specific agent summaries are installed yet.",
    "",
    ...gitSafetyWarning,
    "## Installed Packs",
    "",
    ...(packs.length > 0
      ? packs.map((pack) => `- ${pack.manifest.name}: ${pack.manifest.title}`)
      : ["- No packs installed"]),
    "",
    "## Detected Project",
    "",
    `- Framework: ${analysis.framework}`,
    `- Language: ${analysis.language}`,
    `- Package manager: ${analysis.packageManager}`,
    "",
    "## Notes",
    "",
    "Detailed Codex skills live in `.agents/skills`.",
    "Pack sources live in `.contextforge/packs`.",
    "Pack-specific agent summaries live in `.contextforge/instructions/agents`."
  ].join("\n");
}

function compileRootClaude(packs: InstalledPack[]): string {
  const summaries = packs
    .map((pack) => pack.files.claude?.trim())
    .filter((summary): summary is string => Boolean(summary));
  const gitSafetyWarning = packs.some((pack) => pack.manifest.name === "git-workflow")
    ? [
        "## Git Safety",
        "",
        "Do not commit, push, merge, rebase, reset, delete branches, or rewrite history unless explicitly requested by the user.",
        ""
      ]
    : [];

  return [
    "# Claude Code Instructions",
    "",
    "Generated by ContextForge from installed instruction packs.",
    "",
    "## Core Behavior",
    "",
    summaries.length > 0 ? summaries.join("\n\n") : "No pack-specific Claude summaries are installed yet.",
    "",
    ...gitSafetyWarning,
    "## Installed Packs",
    "",
    ...(packs.length > 0
      ? packs.map((pack) => `- ${pack.manifest.name}: ${pack.manifest.title}`)
      : ["- No packs installed"]),
    "",
    "## Notes",
    "",
    "Keep this file concise.",
    "Detailed pack sources live in `.contextforge/packs`.",
    "Pack-specific Claude summaries live in `.contextforge/instructions/claude`."
  ].join("\n");
}

export function compileOutputs(
  config: ContextForgeConfig,
  packs: InstalledPack[],
  analysis: ProjectAnalysis
): GeneratedFile[] {
  const outputs: GeneratedFile[] = [];

  for (const pack of packs) {
    for (const file of pack.manifest.files) {
      if (!shouldGenerateFile(file.type, config.tools)) {
        continue;
      }

      const content = pack.files[file.type];
      const outputPath = file.output ?? defaultOutput(pack.manifest.name, file.type);

      if (!content || !outputPath) {
        continue;
      }

      outputs.push({
        path: normalizeOutputPath(outputPath),
        content
      });
    }
  }

  if (config.tools.includes("codex")) {
    outputs.push({ path: "AGENTS.md", content: compileRootAgents(packs, analysis) });
  }

  if (config.tools.includes("claude")) {
    outputs.push({ path: "CLAUDE.md", content: compileRootClaude(packs) });
  }

  return outputs;
}
