import type { ProjectAnalysis } from "../types.js";
import type { LoadedPack } from "../registry/registrySchema.js";
import { packageManagerLabel } from "../registry/resolvePack.js";

export function compileAgentsMd(analysis: ProjectAnalysis, packs: LoadedPack[]): string {
  return [
    "# ContextForge Instructions",
    "",
    "Generated by ContextForge. Add project-specific guidance outside this block.",
    "",
    "## Detected Project",
    `- Framework: ${analysis.framework}`,
    `- Language: ${analysis.language}`,
    `- Package manager: ${packageManagerLabel(analysis.packageManager)}`,
    `- Styling: ${analysis.styling.tailwind ? "Tailwind CSS" : "not detected"}${analysis.styling.shadcn ? " + shadcn/ui" : ""}`,
    `- Database: ${analysis.database.prisma ? "Prisma" : analysis.database.drizzle ? "Drizzle" : "not detected"}`,
    `- Testing: ${[
      analysis.testing.vitest && "Vitest",
      analysis.testing.jest && "Jest",
      analysis.testing.playwright && "Playwright"
    ]
      .filter(Boolean)
      .join(", ") || "not detected"}`,
    "",
    "## Active Packs",
    ...packs.flatMap((pack) => [
      "",
      `### ${pack.title}`,
      "",
      pack.description,
      "",
      pack.files.rules.trim()
    ])
  ].join("\n");
}
