import path from "node:path";
import fs from "fs-extra";
import type { InstalledPack } from "../registry/registrySchema.js";
import { GENERATED_BLOCK_END, GENERATED_BLOCK_START } from "../fs/updateGeneratedBlock.js";

const AGENTS_INSTRUCTIONS_DIR = ".contextforge/instructions/agents";

async function readInstructionSummaries(root: string): Promise<string[]> {
  const directory = path.join(root, AGENTS_INSTRUCTIONS_DIR);

  if (!(await fs.pathExists(directory))) {
    return [];
  }

  const files = (await fs.readdir(directory))
    .filter((file) => file.endsWith(".md"))
    .sort((a, b) => a.localeCompare(b));

  return Promise.all(files.map((file) => fs.readFile(path.join(directory, file), "utf8")));
}

export async function compileAgentsMd(root: string, packs: InstalledPack[]): Promise<string> {
  const summaries = await readInstructionSummaries(root);
  const gitSafetyWarning = packs.some((pack) => pack.manifest.name === "git-workflow")
    ? [
        "## Git Safety",
        "",
        "Do not commit, push, merge, rebase, reset, delete branches, or rewrite history unless explicitly requested by the user.",
        ""
      ]
    : [];

  return [
    "# Project Agent Instructions",
    "",
    GENERATED_BLOCK_START,
    "Generated by ContextForge from installed instruction packs.",
    "",
    "## Core Behavior",
    "",
    summaries.length > 0
      ? summaries.map((summary) => summary.trim()).join("\n\n")
      : "No pack-specific agent summaries are installed yet.",
    "",
    ...gitSafetyWarning,
    "## Installed Packs",
    "",
    ...(packs.length > 0
      ? packs.map((pack) => `- ${pack.manifest.name}: ${pack.manifest.title}`)
      : ["- No packs installed"]),
    "",
    "## Notes",
    "",
    "Detailed Codex skills live in `.agents/skills`.",
    "Pack sources live in `.contextforge/packs`.",
    "Pack-specific agent summaries live in `.contextforge/instructions/agents`.",
    "",
    GENERATED_BLOCK_END
  ].join("\n");
}
